<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2013sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<DOCUMENT>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">E:/koufana/GUCE/PROJETS/SIAT/LISTED~1/AP/AIE_MINADER.xsd</xsl:attribute>
			<xsl:for-each select="DOCUMENT">
				<xsl:variable name="var1_resultof_first" select="REFERENCE_DOSSIER"/>
				<xsl:variable name="var2_resultof_first" select="MESSAGE"/>
				<xsl:variable name="var3_resultof_first" select="ROUTAGE"/>
				<TYPE_DOCUMENT>
					<xsl:value-of select="string(TYPE_DOCUMENT)"/>
				</TYPE_DOCUMENT>
				<MESSAGE>
					<TYPE_MESSAGE>
						<xsl:value-of select="string($var2_resultof_first/TYPE_MESSAGE)"/>
					</TYPE_MESSAGE>
					<DATE_EMISSION>
						<xsl:value-of select="string($var2_resultof_first/DATE_EMISSION)"/>
					</DATE_EMISSION>
					<ETAT>
						<xsl:value-of select="string($var2_resultof_first/ETAT)"/>
					</ETAT>
					<NUMERO_MESSAGE>
						<xsl:value-of select="string($var2_resultof_first/NUMERO_MESSAGE)"/>
					</NUMERO_MESSAGE>
					<NUMERO_MESSAGE_ORIGINE>
						<xsl:value-of select="string($var2_resultof_first/NUMERO_MESSAGE_ORIGINE)"/>
					</NUMERO_MESSAGE_ORIGINE>
					<DATE_EMISSION_MSG_ORIGINE>
						<xsl:value-of select="string($var2_resultof_first/DATE_EMISSION_MSG_ORIGINE)"/>
					</DATE_EMISSION_MSG_ORIGINE>
				</MESSAGE>
				<REFERENCE_DOSSIER>
					<NUMERO_DOSSIER>
						<xsl:value-of select="string($var1_resultof_first/NUMERO_DOSSIER)"/>
					</NUMERO_DOSSIER>
					<NUMERO_DEMANDE>
						<xsl:value-of select="string($var1_resultof_first/NUMERO_DEMANDE)"/>
					</NUMERO_DEMANDE>
					<SERVICE>
						<xsl:value-of select="string($var1_resultof_first/SERVICE)"/>
					</SERVICE>
					<REFERENCE_GUCE>
						<xsl:value-of select="string($var1_resultof_first/REFERENCE_GUCE)"/>
					</REFERENCE_GUCE>
					<REFERENCE_SIAT>
						<xsl:value-of select="string($var1_resultof_first/REFERENCE_SIAT)"/>
					</REFERENCE_SIAT>
					<DATE_CREATION>
						<xsl:value-of select="string($var1_resultof_first/DATE_CREATION)"/>
					</DATE_CREATION>
				</REFERENCE_DOSSIER>
				<ROUTAGE>
					<EMETTEUR>
						<xsl:value-of select="string($var3_resultof_first/EMETTEUR)"/>
					</EMETTEUR>
					<DESTINATAIRE>
						<xsl:value-of select="string($var3_resultof_first/DESTINATAIRE)"/>
					</DESTINATAIRE>
				</ROUTAGE>
				<xsl:for-each select="ERREURS">
					<ERREURS>
						<xsl:for-each select="ERREUR">
							<ERREUR>
								<xsl:for-each select="CODE_ERREUR">
									<CODE_ERREUR>
										<xsl:value-of select="string(.)"/>
									</CODE_ERREUR>
								</xsl:for-each>
								<xsl:for-each select="LIBELLE_ERREUR">
									<LIBELLE_ERREUR>
										<xsl:value-of select="string(.)"/>
									</LIBELLE_ERREUR>
								</xsl:for-each>
								<xsl:for-each select="REFERENCE_DONNEE">
									<REFERENCE_DONNEE>
										<xsl:value-of select="string(.)"/>
									</REFERENCE_DONNEE>
								</xsl:for-each>
							</ERREUR>
						</xsl:for-each>
					</ERREURS>
				</xsl:for-each>
				<CONTENT>
					<xsl:for-each select="CONTENT/DECISION_ORGANISME">
						<DECISION_ORGANISME>
							<xsl:for-each select="CODE">
								<CODE>
									<xsl:value-of select="string(.)"/>
								</CODE>
							</xsl:for-each>
							<xsl:for-each select="LIBELLE">
								<LIBELLE>
									<xsl:value-of select="string(.)"/>
								</LIBELLE>
							</xsl:for-each>
							<xsl:for-each select="OBSERVATION">
								<OBSERVATION>
									<xsl:value-of select="string(.)"/>
								</OBSERVATION>
							</xsl:for-each>
						</DECISION_ORGANISME>
					</xsl:for-each>
					<xsl:for-each select="CONTENT/CODE_BUREAU">
						<CODE_BUREAU>
							<xsl:value-of select="string(.)"/>
						</CODE_BUREAU>
					</xsl:for-each>
					<xsl:for-each select="CONTENT/CLIENT">
						<CLIENT>
							<xsl:for-each select="NUMERO_CONTRIBUABLE">
								<NUMERO_CONTRIBUABLE>
									<xsl:value-of select="string(.)"/>
								</NUMERO_CONTRIBUABLE>
							</xsl:for-each>
							<xsl:for-each select="RAISON_SOCIALE">
								<RAISON_SOCIALE>
									<xsl:value-of select="string(.)"/>
								</RAISON_SOCIALE>
							</xsl:for-each>
							<xsl:for-each select="AGREMENT_COMMERCE">
								<AGREMENT_COMMERCE>
									<xsl:for-each select="NUMERO_INSCRIPTION_FICHIER">
										<NUMERO_INSCRIPTION_FICHIER>
											<xsl:value-of select="string(.)"/>
										</NUMERO_INSCRIPTION_FICHIER>
									</xsl:for-each>
									<xsl:for-each select="DATE_OBTENTION">
										<DATE_OBTENTION>
											<xsl:value-of select="string(.)"/>
										</DATE_OBTENTION>
									</xsl:for-each>
									<xsl:for-each select="DATE_VALIDITE">
										<DATE_VALIDITE>
											<xsl:value-of select="string(.)"/>
										</DATE_VALIDITE>
									</xsl:for-each>
									<xsl:for-each select="NUMERO_CARTE_COMMERCANT">
										<NUMERO_CARTE_COMMERCANT>
											<xsl:value-of select="string(.)"/>
										</NUMERO_CARTE_COMMERCANT>
									</xsl:for-each>
								</AGREMENT_COMMERCE>
							</xsl:for-each>
							<xsl:for-each select="AGREMENT_METIER">
								<AGREMENT_METIER>
									<xsl:for-each select="TYPE_AGREMENT">
										<TYPE_AGREMENT>
											<xsl:value-of select="string(.)"/>
										</TYPE_AGREMENT>
									</xsl:for-each>
									<xsl:for-each select="NUMERO_AGREMENT">
										<NUMERO_AGREMENT>
											<xsl:value-of select="string(.)"/>
										</NUMERO_AGREMENT>
									</xsl:for-each>
									<xsl:for-each select="DATE_AGREMENT">
										<DATE_AGREMENT>
											<xsl:value-of select="string(.)"/>
										</DATE_AGREMENT>
									</xsl:for-each>
									<xsl:for-each select="DATE_VALIDITE">
										<DATE_VALIDITE>
											<xsl:value-of select="string(.)"/>
										</DATE_VALIDITE>
									</xsl:for-each>
								</AGREMENT_METIER>
							</xsl:for-each>
							<xsl:for-each select="PERMIS">
								<PERMIS>
									<xsl:for-each select="NUMERO_PERMIS">
										<NUMERO_PERMIS>
											<xsl:value-of select="string(.)"/>
										</NUMERO_PERMIS>
									</xsl:for-each>
									<xsl:for-each select="DATE_OBTENTION">
										<DATE_OBTENTION>
											<xsl:value-of select="string(.)"/>
										</DATE_OBTENTION>
									</xsl:for-each>
									<xsl:for-each select="DATE_VALIDITE">
										<DATE_VALIDITE>
											<xsl:value-of select="string(.)"/>
										</DATE_VALIDITE>
									</xsl:for-each>
									<xsl:for-each select="TYPE">
										<TYPE>
											<xsl:value-of select="string(.)"/>
										</TYPE>
									</xsl:for-each>
								</PERMIS>
							</xsl:for-each>
							<xsl:for-each select="PROFESSION">
								<PROFESSION>
									<xsl:value-of select="string(.)"/>
								</PROFESSION>
							</xsl:for-each>
							<xsl:for-each select="NUMERO_REGISTRE_COMMERCE">
								<NUMERO_REGISTRE_COMMERCE>
									<xsl:value-of select="string(.)"/>
								</NUMERO_REGISTRE_COMMERCE>
							</xsl:for-each>
							<xsl:for-each select="CNI">
								<CNI>
									<xsl:value-of select="string(.)"/>
								</CNI>
							</xsl:for-each>
							<xsl:for-each select="ADRESSE">
								<ADRESSE>
									<xsl:for-each select="ADRESSE1">
										<ADRESSE1>
											<xsl:value-of select="string(.)"/>
										</ADRESSE1>
									</xsl:for-each>
									<xsl:for-each select="ADRESSE2">
										<ADRESSE2>
											<xsl:value-of select="string(.)"/>
										</ADRESSE2>
									</xsl:for-each>
									<xsl:for-each select="BP">
										<BP>
											<xsl:value-of select="string(.)"/>
										</BP>
									</xsl:for-each>
									<xsl:for-each select="PAYS_ADRESSE">
										<PAYS_ADRESSE>
											<xsl:for-each select="CODE_PAYS">
												<CODE_PAYS>
													<xsl:value-of select="string(.)"/>
												</CODE_PAYS>
											</xsl:for-each>
											<xsl:for-each select="NOM_PAYS">
												<NOM_PAYS>
													<xsl:value-of select="string(.)"/>
												</NOM_PAYS>
											</xsl:for-each>
										</PAYS_ADRESSE>
									</xsl:for-each>
									<xsl:for-each select="VILLE">
										<VILLE>
											<xsl:value-of select="string(.)"/>
										</VILLE>
									</xsl:for-each>
									<xsl:for-each select="EMAIL">
										<EMAIL>
											<xsl:value-of select="string(.)"/>
										</EMAIL>
									</xsl:for-each>
									<xsl:for-each select="SITE_WEB">
										<SITE_WEB>
											<xsl:value-of select="string(.)"/>
										</SITE_WEB>
									</xsl:for-each>
								</ADRESSE>
							</xsl:for-each>
							<xsl:for-each select="TELEPHONE_FIXE">
								<TELEPHONE_FIXE>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</TELEPHONE_FIXE>
							</xsl:for-each>
							<xsl:for-each select="TELEPHONE_MOBILE">
								<TELEPHONE_MOBILE>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</TELEPHONE_MOBILE>
							</xsl:for-each>
							<xsl:for-each select="FAX">
								<FAX>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</FAX>
							</xsl:for-each>
						</CLIENT>
					</xsl:for-each>
					<xsl:for-each select="CONTENT/PROMOTEUR">
						<PROMOTEUR>
							<xsl:for-each select="RAISON_SOCIALE">
								<RAISON_SOCIALE>
									<xsl:value-of select="string(.)"/>
								</RAISON_SOCIALE>
							</xsl:for-each>
							<xsl:for-each select="ADRESSE">
								<ADRESSE>
									<xsl:for-each select="ADRESSE1">
										<ADRESSE1>
											<xsl:value-of select="string(.)"/>
										</ADRESSE1>
									</xsl:for-each>
									<xsl:for-each select="ADRESSE2">
										<ADRESSE2>
											<xsl:value-of select="string(.)"/>
										</ADRESSE2>
									</xsl:for-each>
									<xsl:for-each select="BP">
										<BP>
											<xsl:value-of select="string(.)"/>
										</BP>
									</xsl:for-each>
									<xsl:for-each select="PAYS_ADRESSE">
										<PAYS_ADRESSE>
											<xsl:for-each select="CODE_PAYS">
												<CODE_PAYS>
													<xsl:value-of select="string(.)"/>
												</CODE_PAYS>
											</xsl:for-each>
											<xsl:for-each select="NOM_PAYS">
												<NOM_PAYS>
													<xsl:value-of select="string(.)"/>
												</NOM_PAYS>
											</xsl:for-each>
										</PAYS_ADRESSE>
									</xsl:for-each>
									<xsl:for-each select="VILLE">
										<VILLE>
											<xsl:value-of select="string(.)"/>
										</VILLE>
									</xsl:for-each>
									<xsl:for-each select="EMAIL">
										<EMAIL>
											<xsl:value-of select="string(.)"/>
										</EMAIL>
									</xsl:for-each>
									<xsl:for-each select="SITE_WEB">
										<SITE_WEB>
											<xsl:value-of select="string(.)"/>
										</SITE_WEB>
									</xsl:for-each>
								</ADRESSE>
							</xsl:for-each>
							<xsl:for-each select="TELEPHONE_FIXE">
								<TELEPHONE_FIXE>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</TELEPHONE_FIXE>
							</xsl:for-each>
							<xsl:for-each select="TELEPHONE_MOBILE">
								<TELEPHONE_MOBILE>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</TELEPHONE_MOBILE>
							</xsl:for-each>
							<xsl:for-each select="FAX">
								<FAX>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</FAX>
							</xsl:for-each>
						</PROMOTEUR>
					</xsl:for-each>
					<xsl:for-each select="CONTENT/FORMULATEUR">
						<FORMULATEUR>
							<xsl:for-each select="RAISON_SOCIALE">
								<RAISON_SOCIALE>
									<xsl:value-of select="string(.)"/>
								</RAISON_SOCIALE>
							</xsl:for-each>
							<xsl:for-each select="ADRESSE">
								<ADRESSE>
									<xsl:for-each select="ADRESSE1">
										<ADRESSE1>
											<xsl:value-of select="string(.)"/>
										</ADRESSE1>
									</xsl:for-each>
									<xsl:for-each select="ADRESSE2">
										<ADRESSE2>
											<xsl:value-of select="string(.)"/>
										</ADRESSE2>
									</xsl:for-each>
									<xsl:for-each select="BP">
										<BP>
											<xsl:value-of select="string(.)"/>
										</BP>
									</xsl:for-each>
									<xsl:for-each select="PAYS_ADRESSE">
										<PAYS_ADRESSE>
											<xsl:for-each select="CODE_PAYS">
												<CODE_PAYS>
													<xsl:value-of select="string(.)"/>
												</CODE_PAYS>
											</xsl:for-each>
											<xsl:for-each select="NOM_PAYS">
												<NOM_PAYS>
													<xsl:value-of select="string(.)"/>
												</NOM_PAYS>
											</xsl:for-each>
										</PAYS_ADRESSE>
									</xsl:for-each>
									<xsl:for-each select="VILLE">
										<VILLE>
											<xsl:value-of select="string(.)"/>
										</VILLE>
									</xsl:for-each>
									<xsl:for-each select="EMAIL">
										<EMAIL>
											<xsl:value-of select="string(.)"/>
										</EMAIL>
									</xsl:for-each>
									<xsl:for-each select="SITE_WEB">
										<SITE_WEB>
											<xsl:value-of select="string(.)"/>
										</SITE_WEB>
									</xsl:for-each>
								</ADRESSE>
							</xsl:for-each>
							<xsl:for-each select="TELEPHONE_FIXE">
								<TELEPHONE_FIXE>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</TELEPHONE_FIXE>
							</xsl:for-each>
							<xsl:for-each select="TELEPHONE_MOBILE">
								<TELEPHONE_MOBILE>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</TELEPHONE_MOBILE>
							</xsl:for-each>
							<xsl:for-each select="FAX">
								<FAX>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</FAX>
							</xsl:for-each>
						</FORMULATEUR>
					</xsl:for-each>
					<xsl:for-each select="CONTENT/FABRICANT_MATIERE_ACTIVE">
						<FABRICANT_MATIERE_ACTIVE>
							<xsl:for-each select="RAISON_SOCIALE">
								<RAISON_SOCIALE>
									<xsl:value-of select="string(.)"/>
								</RAISON_SOCIALE>
							</xsl:for-each>
							<xsl:for-each select="ADRESSE">
								<ADRESSE>
									<xsl:for-each select="ADRESSE1">
										<ADRESSE1>
											<xsl:value-of select="string(.)"/>
										</ADRESSE1>
									</xsl:for-each>
									<xsl:for-each select="ADRESSE2">
										<ADRESSE2>
											<xsl:value-of select="string(.)"/>
										</ADRESSE2>
									</xsl:for-each>
									<xsl:for-each select="BP">
										<BP>
											<xsl:value-of select="string(.)"/>
										</BP>
									</xsl:for-each>
									<xsl:for-each select="PAYS_ADRESSE">
										<PAYS_ADRESSE>
											<xsl:for-each select="CODE_PAYS">
												<CODE_PAYS>
													<xsl:value-of select="string(.)"/>
												</CODE_PAYS>
											</xsl:for-each>
											<xsl:for-each select="NOM_PAYS">
												<NOM_PAYS>
													<xsl:value-of select="string(.)"/>
												</NOM_PAYS>
											</xsl:for-each>
										</PAYS_ADRESSE>
									</xsl:for-each>
									<xsl:for-each select="VILLE">
										<VILLE>
											<xsl:value-of select="string(.)"/>
										</VILLE>
									</xsl:for-each>
									<xsl:for-each select="EMAIL">
										<EMAIL>
											<xsl:value-of select="string(.)"/>
										</EMAIL>
									</xsl:for-each>
									<xsl:for-each select="SITE_WEB">
										<SITE_WEB>
											<xsl:value-of select="string(.)"/>
										</SITE_WEB>
									</xsl:for-each>
								</ADRESSE>
							</xsl:for-each>
							<xsl:for-each select="TELEPHONE_FIXE">
								<TELEPHONE_FIXE>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</TELEPHONE_FIXE>
							</xsl:for-each>
							<xsl:for-each select="TELEPHONE_MOBILE">
								<TELEPHONE_MOBILE>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</TELEPHONE_MOBILE>
							</xsl:for-each>
							<xsl:for-each select="FAX">
								<FAX>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</FAX>
							</xsl:for-each>
						</FABRICANT_MATIERE_ACTIVE>
					</xsl:for-each>
					<xsl:for-each select="CONTENT/REPRESENTANT_CAMEROUN">
						<REPRESENTANT_CAMEROUN>
							<xsl:for-each select="NUMERO_CONTRIBUABLE">
								<NUMERO_CONTRIBUABLE>
									<xsl:value-of select="string(.)"/>
								</NUMERO_CONTRIBUABLE>
							</xsl:for-each>
							<xsl:for-each select="RAISON_SOCIALE">
								<RAISON_SOCIALE>
									<xsl:value-of select="string(.)"/>
								</RAISON_SOCIALE>
							</xsl:for-each>
							<xsl:for-each select="ADRESSE">
								<ADRESSE>
									<xsl:for-each select="ADRESSE1">
										<ADRESSE1>
											<xsl:value-of select="string(.)"/>
										</ADRESSE1>
									</xsl:for-each>
									<xsl:for-each select="ADRESSE2">
										<ADRESSE2>
											<xsl:value-of select="string(.)"/>
										</ADRESSE2>
									</xsl:for-each>
									<xsl:for-each select="BP">
										<BP>
											<xsl:value-of select="string(.)"/>
										</BP>
									</xsl:for-each>
									<xsl:for-each select="PAYS_ADRESSE">
										<PAYS_ADRESSE>
											<xsl:for-each select="CODE_PAYS">
												<CODE_PAYS>
													<xsl:value-of select="string(.)"/>
												</CODE_PAYS>
											</xsl:for-each>
											<xsl:for-each select="NOM_PAYS">
												<NOM_PAYS>
													<xsl:value-of select="string(.)"/>
												</NOM_PAYS>
											</xsl:for-each>
										</PAYS_ADRESSE>
									</xsl:for-each>
									<xsl:for-each select="VILLE">
										<VILLE>
											<xsl:value-of select="string(.)"/>
										</VILLE>
									</xsl:for-each>
									<xsl:for-each select="EMAIL">
										<EMAIL>
											<xsl:value-of select="string(.)"/>
										</EMAIL>
									</xsl:for-each>
									<xsl:for-each select="SITE_WEB">
										<SITE_WEB>
											<xsl:value-of select="string(.)"/>
										</SITE_WEB>
									</xsl:for-each>
								</ADRESSE>
							</xsl:for-each>
							<xsl:for-each select="TELEPHONE_FIXE">
								<TELEPHONE_FIXE>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</TELEPHONE_FIXE>
							</xsl:for-each>
							<xsl:for-each select="TELEPHONE_MOBILE">
								<TELEPHONE_MOBILE>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</TELEPHONE_MOBILE>
							</xsl:for-each>
							<xsl:for-each select="FAX">
								<FAX>
									<xsl:for-each select="INDICATIF_PAYS">
										<INDICATIF_PAYS>
											<xsl:value-of select="string(.)"/>
										</INDICATIF_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
								</FAX>
							</xsl:for-each>
						</REPRESENTANT_CAMEROUN>
					</xsl:for-each>
					<xsl:for-each select="CONTENT/INFORMATIONS_GENERALES">
						<INFORMATIONS_GENERALES>
							<xsl:for-each select="CERTIFICAT_EXPERTISE">
								<CERTIFICAT_EXPERTISE>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
									<xsl:for-each select="DATE">
										<DATE>
											<xsl:value-of select="string(.)"/>
										</DATE>
									</xsl:for-each>
								</CERTIFICAT_EXPERTISE>
							</xsl:for-each>
							<xsl:for-each select="CONTRAT_COMMERCIAL">
								<CONTRAT_COMMERCIAL>
									<xsl:for-each select="TYPE">
										<TYPE>
											<xsl:value-of select="string(.)"/>
										</TYPE>
									</xsl:for-each>
									<xsl:for-each select="NUMERO">
										<NUMERO>
											<xsl:value-of select="string(.)"/>
										</NUMERO>
									</xsl:for-each>
									<xsl:for-each select="DATE">
										<DATE>
											<xsl:value-of select="string(.)"/>
										</DATE>
									</xsl:for-each>
								</CONTRAT_COMMERCIAL>
							</xsl:for-each>
							<xsl:for-each select="TRANSPORT">
								<TRANSPORT>
									<xsl:for-each select="MOYEN_TRANSPORT">
										<MOYEN_TRANSPORT>
											<xsl:for-each select="CODE">
												<CODE>
													<xsl:value-of select="string(.)"/>
												</CODE>
											</xsl:for-each>
											<xsl:for-each select="LIBELLE">
												<LIBELLE>
													<xsl:value-of select="string(.)"/>
												</LIBELLE>
											</xsl:for-each>
										</MOYEN_TRANSPORT>
									</xsl:for-each>
									<xsl:for-each select="MODE_TRANSPORT">
										<MODE_TRANSPORT>
											<xsl:for-each select="CODE">
												<CODE>
													<xsl:value-of select="string(.)"/>
												</CODE>
											</xsl:for-each>
											<xsl:for-each select="LIBELLE">
												<LIBELLE>
													<xsl:value-of select="string(.)"/>
												</LIBELLE>
											</xsl:for-each>
										</MODE_TRANSPORT>
									</xsl:for-each>
									<xsl:for-each select="DATE_ARRIVEE_DEPART">
										<DATE_ARRIVEE_DEPART>
											<xsl:value-of select="string(.)"/>
										</DATE_ARRIVEE_DEPART>
									</xsl:for-each>
									<xsl:for-each select="NUM_CONNAISSEMENT_LTA">
										<NUM_CONNAISSEMENT_LTA>
											<xsl:value-of select="string(.)"/>
										</NUM_CONNAISSEMENT_LTA>
									</xsl:for-each>
								</TRANSPORT>
							</xsl:for-each>
							<xsl:for-each select="LIEU_EXPORTATION">
								<LIEU_EXPORTATION>
									<xsl:for-each select="UNLOCODE">
										<UNLOCODE>
											<xsl:value-of select="string(.)"/>
										</UNLOCODE>
									</xsl:for-each>
									<xsl:for-each select="LIBELLE">
										<LIBELLE>
											<xsl:value-of select="string(.)"/>
										</LIBELLE>
									</xsl:for-each>
								</LIEU_EXPORTATION>
							</xsl:for-each>
							<xsl:for-each select="LIEU_CHARGEMENT">
								<LIEU_CHARGEMENT>
									<xsl:for-each select="UNLOCODE">
										<UNLOCODE>
											<xsl:value-of select="string(.)"/>
										</UNLOCODE>
									</xsl:for-each>
									<xsl:for-each select="LIBELLE">
										<LIBELLE>
											<xsl:value-of select="string(.)"/>
										</LIBELLE>
									</xsl:for-each>
								</LIEU_CHARGEMENT>
							</xsl:for-each>
							<xsl:for-each select="LIEU_TRANSIT">
								<LIEU_TRANSIT>
									<xsl:for-each select="UNLOCODE">
										<UNLOCODE>
											<xsl:value-of select="string(.)"/>
										</UNLOCODE>
									</xsl:for-each>
									<xsl:for-each select="LIBELLE">
										<LIBELLE>
											<xsl:value-of select="string(.)"/>
										</LIBELLE>
									</xsl:for-each>
								</LIEU_TRANSIT>
							</xsl:for-each>
							<xsl:for-each select="LIEU_DECHARGEMENT">
								<LIEU_DECHARGEMENT>
									<xsl:for-each select="UNLOCODE">
										<UNLOCODE>
											<xsl:value-of select="string(.)"/>
										</UNLOCODE>
									</xsl:for-each>
									<xsl:for-each select="LIBELLE">
										<LIBELLE>
											<xsl:value-of select="string(.)"/>
										</LIBELLE>
									</xsl:for-each>
								</LIEU_DECHARGEMENT>
							</xsl:for-each>
							<xsl:for-each select="PERMIS">
								<PERMIS>
									<xsl:for-each select="NUMERO_PERMIS">
										<NUMERO_PERMIS>
											<xsl:value-of select="string(.)"/>
										</NUMERO_PERMIS>
									</xsl:for-each>
									<xsl:for-each select="DATE">
										<DATE>
											<xsl:value-of select="string(.)"/>
										</DATE>
									</xsl:for-each>
									<xsl:for-each select="DELIVREUR">
										<DELIVREUR>
											<xsl:for-each select="RAISON_SOCIALE">
												<RAISON_SOCIALE>
													<xsl:value-of select="string(.)"/>
												</RAISON_SOCIALE>
											</xsl:for-each>
											<xsl:for-each select="ADRESSE">
												<ADRESSE>
													<xsl:for-each select="ADRESSE1">
														<ADRESSE1>
															<xsl:value-of select="string(.)"/>
														</ADRESSE1>
													</xsl:for-each>
													<xsl:for-each select="ADRESSE2">
														<ADRESSE2>
															<xsl:value-of select="string(.)"/>
														</ADRESSE2>
													</xsl:for-each>
													<xsl:for-each select="BP">
														<BP>
															<xsl:value-of select="string(.)"/>
														</BP>
													</xsl:for-each>
													<xsl:for-each select="PAYS_ADRESSE">
														<PAYS_ADRESSE>
															<xsl:for-each select="CODE_PAYS">
																<CODE_PAYS>
																	<xsl:value-of select="string(.)"/>
																</CODE_PAYS>
															</xsl:for-each>
															<xsl:for-each select="NOM_PAYS">
																<NOM_PAYS>
																	<xsl:value-of select="string(.)"/>
																</NOM_PAYS>
															</xsl:for-each>
														</PAYS_ADRESSE>
													</xsl:for-each>
													<xsl:for-each select="VILLE">
														<VILLE>
															<xsl:value-of select="string(.)"/>
														</VILLE>
													</xsl:for-each>
													<xsl:for-each select="EMAIL">
														<EMAIL>
															<xsl:value-of select="string(.)"/>
														</EMAIL>
													</xsl:for-each>
													<xsl:for-each select="SITE_WEB">
														<SITE_WEB>
															<xsl:value-of select="string(.)"/>
														</SITE_WEB>
													</xsl:for-each>
												</ADRESSE>
											</xsl:for-each>
											<xsl:for-each select="TELEPHONE_FIXE">
												<TELEPHONE_FIXE>
													<xsl:for-each select="INDICATIF_PAYS">
														<INDICATIF_PAYS>
															<xsl:value-of select="string(.)"/>
														</INDICATIF_PAYS>
													</xsl:for-each>
													<xsl:for-each select="NUMERO">
														<NUMERO>
															<xsl:value-of select="string(.)"/>
														</NUMERO>
													</xsl:for-each>
												</TELEPHONE_FIXE>
											</xsl:for-each>
											<xsl:for-each select="TELEPHONE_MOBILE">
												<TELEPHONE_MOBILE>
													<xsl:for-each select="INDICATIF_PAYS">
														<INDICATIF_PAYS>
															<xsl:value-of select="string(.)"/>
														</INDICATIF_PAYS>
													</xsl:for-each>
													<xsl:for-each select="NUMERO">
														<NUMERO>
															<xsl:value-of select="string(.)"/>
														</NUMERO>
													</xsl:for-each>
												</TELEPHONE_MOBILE>
											</xsl:for-each>
											<xsl:for-each select="FAX">
												<FAX>
													<xsl:for-each select="INDICATIF_PAYS">
														<INDICATIF_PAYS>
															<xsl:value-of select="string(.)"/>
														</INDICATIF_PAYS>
													</xsl:for-each>
													<xsl:for-each select="NUMERO">
														<NUMERO>
															<xsl:value-of select="string(.)"/>
														</NUMERO>
													</xsl:for-each>
												</FAX>
											</xsl:for-each>
										</DELIVREUR>
									</xsl:for-each>
									<xsl:for-each select="PAYS">
										<PAYS>
											<xsl:for-each select="CODE_PAYS">
												<CODE_PAYS>
													<xsl:value-of select="string(.)"/>
												</CODE_PAYS>
											</xsl:for-each>
											<xsl:for-each select="NOM_PAYS">
												<NOM_PAYS>
													<xsl:value-of select="string(.)"/>
												</NOM_PAYS>
											</xsl:for-each>
										</PAYS>
									</xsl:for-each>
								</PERMIS>
							</xsl:for-each>
							<xsl:for-each select="SIGNATAIRE">
								<SIGNATAIRE>
									<xsl:for-each select="NOM">
										<NOM>
											<xsl:value-of select="string(.)"/>
										</NOM>
									</xsl:for-each>
									<xsl:for-each select="QUALITE">
										<QUALITE>
											<xsl:value-of select="string(.)"/>
										</QUALITE>
									</xsl:for-each>
									<xsl:for-each select="LIEU">
										<LIEU>
											<xsl:value-of select="string(.)"/>
										</LIEU>
									</xsl:for-each>
									<xsl:for-each select="DATE">
										<DATE>
											<xsl:value-of select="string(.)"/>
										</DATE>
									</xsl:for-each>
								</SIGNATAIRE>
							</xsl:for-each>
							<xsl:for-each select="LETTRE_TRANSPORT">
								<LETTRE_TRANSPORT>
									<xsl:for-each select="NUMERO_ESCALE">
										<NUMERO_ESCALE>
											<xsl:value-of select="string(.)"/>
										</NUMERO_ESCALE>
									</xsl:for-each>
									<xsl:for-each select="TYPE_LETTRE_TRANSPORT">
										<TYPE_LETTRE_TRANSPORT>
											<xsl:value-of select="string(.)"/>
										</TYPE_LETTRE_TRANSPORT>
									</xsl:for-each>
									<xsl:for-each select="NUMERO_Lettre_TRANSPORT">
										<NUMERO_Lettre_TRANSPORT>
											<xsl:value-of select="string(.)"/>
										</NUMERO_Lettre_TRANSPORT>
									</xsl:for-each>
									<xsl:for-each select="DATE_LETTRE_TRANSPORT">
										<DATE_LETTRE_TRANSPORT>
											<xsl:value-of select="string(.)"/>
										</DATE_LETTRE_TRANSPORT>
									</xsl:for-each>
								</LETTRE_TRANSPORT>
							</xsl:for-each>
							<xsl:for-each select="PAYS_ORIGINE">
								<PAYS_ORIGINE>
									<xsl:for-each select="CODE_PAYS">
										<CODE_PAYS>
											<xsl:value-of select="string(.)"/>
										</CODE_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NOM_PAYS">
										<NOM_PAYS>
											<xsl:value-of select="string(.)"/>
										</NOM_PAYS>
									</xsl:for-each>
								</PAYS_ORIGINE>
							</xsl:for-each>
							<xsl:for-each select="PAYS_DESTINATION">
								<PAYS_DESTINATION>
									<xsl:for-each select="CODE_PAYS">
										<CODE_PAYS>
											<xsl:value-of select="string(.)"/>
										</CODE_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NOM_PAYS">
										<NOM_PAYS>
											<xsl:value-of select="string(.)"/>
										</NOM_PAYS>
									</xsl:for-each>
								</PAYS_DESTINATION>
							</xsl:for-each>
							<xsl:for-each select="PAYS_PROVENANCE">
								<PAYS_PROVENANCE>
									<xsl:for-each select="CODE_PAYS">
										<CODE_PAYS>
											<xsl:value-of select="string(.)"/>
										</CODE_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NOM_PAYS">
										<NOM_PAYS>
											<xsl:value-of select="string(.)"/>
										</NOM_PAYS>
									</xsl:for-each>
								</PAYS_PROVENANCE>
							</xsl:for-each>
							<xsl:for-each select="PAYS_TRANSIT">
								<PAYS_TRANSIT>
									<xsl:for-each select="CODE_PAYS">
										<CODE_PAYS>
											<xsl:value-of select="string(.)"/>
										</CODE_PAYS>
									</xsl:for-each>
									<xsl:for-each select="NOM_PAYS">
										<NOM_PAYS>
											<xsl:value-of select="string(.)"/>
										</NOM_PAYS>
									</xsl:for-each>
								</PAYS_TRANSIT>
							</xsl:for-each>
							<xsl:for-each select="CONDITIONS">
								<CONDITIONS>
									<xsl:value-of select="string(.)"/>
								</CONDITIONS>
							</xsl:for-each>
							<xsl:for-each select="TERMES_VENTE">
								<TERMES_VENTE>
									<xsl:for-each select="CODE">
										<CODE>
											<xsl:value-of select="string(.)"/>
										</CODE>
									</xsl:for-each>
									<xsl:for-each select="LIBELLE">
										<LIBELLE>
											<xsl:value-of select="string(.)"/>
										</LIBELLE>
									</xsl:for-each>
									<xsl:for-each select="CODE_DEVISE">
										<CODE_DEVISE>
											<xsl:value-of select="string(.)"/>
										</CODE_DEVISE>
									</xsl:for-each>
									<xsl:for-each select="MONTANT">
										<MONTANT>
											<xsl:value-of select="string(.)"/>
										</MONTANT>
									</xsl:for-each>
									<xsl:for-each select="MONTANT_TOTAL_DEVISE">
										<MONTANT_TOTAL_DEVISE>
											<xsl:value-of select="string(.)"/>
										</MONTANT_TOTAL_DEVISE>
									</xsl:for-each>
									<xsl:for-each select="MONTANT_TOTAL_FCFA">
										<MONTANT_TOTAL_FCFA>
											<xsl:value-of select="string(.)"/>
										</MONTANT_TOTAL_FCFA>
									</xsl:for-each>
								</TERMES_VENTE>
							</xsl:for-each>
							<xsl:for-each select="POINT_ENTREE">
								<POINT_ENTREE>
									<xsl:for-each select="UNLOCODE">
										<UNLOCODE>
											<xsl:value-of select="string(.)"/>
										</UNLOCODE>
									</xsl:for-each>
									<xsl:for-each select="LIBELLE">
										<LIBELLE>
											<xsl:value-of select="string(.)"/>
										</LIBELLE>
									</xsl:for-each>
								</POINT_ENTREE>
							</xsl:for-each>
							<xsl:for-each select="AGREMENT">
								<AGREMENT>
									<xsl:for-each select="TYPE">
										<TYPE>
											<xsl:value-of select="string(.)"/>
										</TYPE>
									</xsl:for-each>
									<xsl:for-each select="REFERENCE">
										<REFERENCE>
											<xsl:value-of select="string(.)"/>
										</REFERENCE>
									</xsl:for-each>
									<xsl:for-each select="DATE">
										<DATE>
											<xsl:value-of select="string(.)"/>
										</DATE>
									</xsl:for-each>
								</AGREMENT>
							</xsl:for-each>
							<xsl:for-each select="PERMIS_EXPLOITATION">
								<PERMIS_EXPLOITATION>
									<xsl:for-each select="NUMERO_FACTURE">
										<NUMERO_FACTURE>
											<xsl:value-of select="string(.)"/>
										</NUMERO_FACTURE>
									</xsl:for-each>
									<xsl:for-each select="DATE_FACTURE">
										<DATE_FACTURE>
											<xsl:value-of select="string(.)"/>
										</DATE_FACTURE>
									</xsl:for-each>
									<xsl:for-each select="VALIDITE">
										<VALIDITE>
											<xsl:value-of select="string(.)"/>
										</VALIDITE>
									</xsl:for-each>
									<xsl:for-each select="TITULAIRE">
										<TITULAIRE>
											<xsl:value-of select="string(.)"/>
										</TITULAIRE>
									</xsl:for-each>
								</PERMIS_EXPLOITATION>
							</xsl:for-each>
							<xsl:for-each select="DESTINATAIRE">
								<DESTINATAIRE>
									<xsl:for-each select="RAISON_SOCIALE">
										<RAISON_SOCIALE>
											<xsl:value-of select="string(.)"/>
										</RAISON_SOCIALE>
									</xsl:for-each>
									<xsl:for-each select="ADRESSE">
										<ADRESSE>
											<xsl:for-each select="ADRESSE1">
												<ADRESSE1>
													<xsl:value-of select="string(.)"/>
												</ADRESSE1>
											</xsl:for-each>
											<xsl:for-each select="ADRESSE2">
												<ADRESSE2>
													<xsl:value-of select="string(.)"/>
												</ADRESSE2>
											</xsl:for-each>
											<xsl:for-each select="BP">
												<BP>
													<xsl:value-of select="string(.)"/>
												</BP>
											</xsl:for-each>
											<xsl:for-each select="PAYS_ADRESSE">
												<PAYS_ADRESSE>
													<xsl:for-each select="CODE_PAYS">
														<CODE_PAYS>
															<xsl:value-of select="string(.)"/>
														</CODE_PAYS>
													</xsl:for-each>
													<xsl:for-each select="NOM_PAYS">
														<NOM_PAYS>
															<xsl:value-of select="string(.)"/>
														</NOM_PAYS>
													</xsl:for-each>
												</PAYS_ADRESSE>
											</xsl:for-each>
											<xsl:for-each select="VILLE">
												<VILLE>
													<xsl:value-of select="string(.)"/>
												</VILLE>
											</xsl:for-each>
											<xsl:for-each select="EMAIL">
												<EMAIL>
													<xsl:value-of select="string(.)"/>
												</EMAIL>
											</xsl:for-each>
											<xsl:for-each select="SITE_WEB">
												<SITE_WEB>
													<xsl:value-of select="string(.)"/>
												</SITE_WEB>
											</xsl:for-each>
										</ADRESSE>
									</xsl:for-each>
									<xsl:for-each select="TELEPHONE_FIXE">
										<TELEPHONE_FIXE>
											<xsl:for-each select="INDICATIF_PAYS">
												<INDICATIF_PAYS>
													<xsl:value-of select="string(.)"/>
												</INDICATIF_PAYS>
											</xsl:for-each>
											<xsl:for-each select="NUMERO">
												<NUMERO>
													<xsl:value-of select="string(.)"/>
												</NUMERO>
											</xsl:for-each>
										</TELEPHONE_FIXE>
									</xsl:for-each>
									<xsl:for-each select="TELEPHONE_MOBILE">
										<TELEPHONE_MOBILE>
											<xsl:for-each select="INDICATIF_PAYS">
												<INDICATIF_PAYS>
													<xsl:value-of select="string(.)"/>
												</INDICATIF_PAYS>
											</xsl:for-each>
											<xsl:for-each select="NUMERO">
												<NUMERO>
													<xsl:value-of select="string(.)"/>
												</NUMERO>
											</xsl:for-each>
										</TELEPHONE_MOBILE>
									</xsl:for-each>
									<xsl:for-each select="FAX">
										<FAX>
											<xsl:for-each select="INDICATIF_PAYS">
												<INDICATIF_PAYS>
													<xsl:value-of select="string(.)"/>
												</INDICATIF_PAYS>
											</xsl:for-each>
											<xsl:for-each select="NUMERO">
												<NUMERO>
													<xsl:value-of select="string(.)"/>
												</NUMERO>
											</xsl:for-each>
										</FAX>
									</xsl:for-each>
								</DESTINATAIRE>
							</xsl:for-each>
							<xsl:for-each select="LIEU_DELIVRANCE">
								<LIEU_DELIVRANCE>
									<xsl:for-each select="LIEU_DELIVRANCE">
										<LIEU_DELIVRANCE>
											<xsl:value-of select="string(.)"/>
										</LIEU_DELIVRANCE>
									</xsl:for-each>
									<xsl:for-each select="ORGANISME">
										<ORGANISME>
											<xsl:value-of select="string(.)"/>
										</ORGANISME>
									</xsl:for-each>
								</LIEU_DELIVRANCE>
							</xsl:for-each>
						</INFORMATIONS_GENERALES>
					</xsl:for-each>
					<xsl:for-each select="CONTENT/SIGNATAIRE">
						<SIGNATAIRE>
							<xsl:for-each select="NOM">
								<NOM>
									<xsl:value-of select="string(.)"/>
								</NOM>
							</xsl:for-each>
							<xsl:for-each select="QUALITE">
								<QUALITE>
									<xsl:value-of select="string(.)"/>
								</QUALITE>
							</xsl:for-each>
							<xsl:for-each select="LIEU">
								<LIEU>
									<xsl:value-of select="string(.)"/>
								</LIEU>
							</xsl:for-each>
							<xsl:for-each select="DATE">
								<DATE>
									<xsl:value-of select="string(.)"/>
								</DATE>
							</xsl:for-each>
						</SIGNATAIRE>
					</xsl:for-each>
					<xsl:for-each select="CONTENT/OBSERVATIONS">
						<OBSERVATIONS>
							<xsl:value-of select="string(.)"/>
						</OBSERVATIONS>
					</xsl:for-each>
					<xsl:for-each select="CONTENT/MARCHANDISES">
						<MARCHANDISES>
							<xsl:for-each select="MARCHANDISE">
								<MARCHANDISE>
									<xsl:for-each select="LINE_NUMBER">
										<LINE_NUMBER>
											<xsl:value-of select="string(floor(number(string(.))))"/>
										</LINE_NUMBER>
									</xsl:for-each>
									<xsl:for-each select="CODE_TARIF">
										<CODE_TARIF>
											<xsl:for-each select="CODE_NSH">
												<CODE_NSH>
													<xsl:value-of select="string(.)"/>
												</CODE_NSH>
											</xsl:for-each>
											<xsl:for-each select="DESIGNATION">
												<DESIGNATION>
													<xsl:value-of select="string(.)"/>
												</DESIGNATION>
											</xsl:for-each>
										</CODE_TARIF>
									</xsl:for-each>
									<xsl:for-each select="SOUS_FAMILLE">
										<SOUS_FAMILLE>
											<xsl:for-each select="CODE_SOUS_FAMILLE">
												<CODE_SOUS_FAMILLE>
													<xsl:value-of select="string(.)"/>
												</CODE_SOUS_FAMILLE>
											</xsl:for-each>
											<xsl:for-each select="NOM">
												<NOM>
													<xsl:value-of select="string(.)"/>
												</NOM>
											</xsl:for-each>
										</SOUS_FAMILLE>
									</xsl:for-each>
									<xsl:for-each select="NOM_COMMERCIAL">
										<NOM_COMMERCIAL>
											<xsl:value-of select="string(.)"/>
										</NOM_COMMERCIAL>
									</xsl:for-each>
									<xsl:for-each select="MATIERE_ACTIVE">
										<MATIERE_ACTIVE>
											<xsl:value-of select="string(.)"/>
										</MATIERE_ACTIVE>
									</xsl:for-each>
									<xsl:for-each select="CONCENTRATION">
										<CONCENTRATION>
											<xsl:value-of select="string(.)"/>
										</CONCENTRATION>
									</xsl:for-each>
									<xsl:for-each select="TYPE_FORMULATION">
										<TYPE_FORMULATION>
											<xsl:value-of select="string(.)"/>
										</TYPE_FORMULATION>
									</xsl:for-each>
									<xsl:for-each select="CLASSE_TOXICOLOGIQUE">
										<CLASSE_TOXICOLOGIQUE>
											<xsl:value-of select="string(.)"/>
										</CLASSE_TOXICOLOGIQUE>
									</xsl:for-each>
									<xsl:for-each select="PAYS_ORIGINE">
										<PAYS_ORIGINE>
											<xsl:for-each select="CODE_PAYS">
												<CODE_PAYS>
													<xsl:value-of select="string(.)"/>
												</CODE_PAYS>
											</xsl:for-each>
											<xsl:for-each select="NOM_PAYS">
												<NOM_PAYS>
													<xsl:value-of select="string(.)"/>
												</NOM_PAYS>
											</xsl:for-each>
										</PAYS_ORIGINE>
									</xsl:for-each>
									<xsl:for-each select="SPECIALITE">
										<SPECIALITE>
											<xsl:value-of select="string(.)"/>
										</SPECIALITE>
									</xsl:for-each>
									<xsl:for-each select="USAGE">
										<USAGE>
											<xsl:value-of select="string(.)"/>
										</USAGE>
									</xsl:for-each>
									<xsl:for-each select="DOSES_UTILISATION">
										<DOSES_UTILISATION>
											<xsl:value-of select="string(.)"/>
										</DOSES_UTILISATION>
									</xsl:for-each>
									<xsl:for-each select="PRESENTATION">
										<PRESENTATION>
											<xsl:value-of select="string(.)"/>
										</PRESENTATION>
									</xsl:for-each>
									<xsl:for-each select="ETIQUETAGE">
										<ETIQUETAGE>
											<xsl:value-of select="string(.)"/>
										</ETIQUETAGE>
									</xsl:for-each>
									<xsl:for-each select="NOM_SCIENTIFIQUE">
										<NOM_SCIENTIFIQUE>
											<xsl:value-of select="string(.)"/>
										</NOM_SCIENTIFIQUE>
									</xsl:for-each>
									<xsl:for-each select="FORMULE_CHIMIQUE">
										<FORMULE_CHIMIQUE>
											<xsl:value-of select="string(.)"/>
										</FORMULE_CHIMIQUE>
									</xsl:for-each>
									<xsl:for-each select="SPECIFICATION_TECHNIQUE">
										<SPECIFICATION_TECHNIQUE>
											<xsl:value-of select="string(.)"/>
										</SPECIFICATION_TECHNIQUE>
									</xsl:for-each>
									<xsl:for-each select="QUANTITE">
										<QUANTITE>
											<xsl:value-of select="string(.)"/>
										</QUANTITE>
									</xsl:for-each>
									<xsl:for-each select="UNITE">
										<UNITE>
											<xsl:value-of select="string(.)"/>
										</UNITE>
									</xsl:for-each>
									<xsl:for-each select="POIDS">
										<POIDS>
											<xsl:value-of select="string(.)"/>
										</POIDS>
									</xsl:for-each>
									<xsl:for-each select="VOLUME">
										<VOLUME>
											<xsl:value-of select="string(.)"/>
										</VOLUME>
									</xsl:for-each>
									<xsl:for-each select="VALEUR_FOB_DEVISE">
										<VALEUR_FOB_DEVISE>
											<xsl:value-of select="string(.)"/>
										</VALEUR_FOB_DEVISE>
									</xsl:for-each>
								</MARCHANDISE>
							</xsl:for-each>
						</MARCHANDISES>
					</xsl:for-each>
					<xsl:for-each select="CONTENT/PIECES_JOINTES">
						<PIECES_JOINTES>
							<xsl:for-each select="PIECE_JOINTE">
								<PIECE_JOINTE>
									<xsl:for-each select="TYPE_PJ">
										<TYPE_PJ>
											<xsl:value-of select="string(.)"/>
										</TYPE_PJ>
									</xsl:for-each>
									<xsl:for-each select="LIBELLE_PJ">
										<LIBELLE_PJ>
											<xsl:value-of select="string(.)"/>
										</LIBELLE_PJ>
									</xsl:for-each>
								</PIECE_JOINTE>
							</xsl:for-each>
						</PIECES_JOINTES>
					</xsl:for-each>
				</CONTENT>
			</xsl:for-each>
		</DOCUMENT>
	</xsl:template>
</xsl:stylesheet>
